name = "fund-manager-presence"
main = "src/index.ts"
compatibility_date = "2026-04-04"
routes = [{ pattern = "gp.hrfuqiang.top/presence/*", zone_name = "hrfuqiang.top" }]

# 本地调试端口
[dev]
port = 8788

[[kv_namespaces]]
binding = "PRESENCE"
id = "eb8f4e665bfd47148a4590cc4886f994"
